### ISSUE TITLE
`alert()` is called repeatedly for same error

### ISSUE THREAD

**Issue by DoxasticFox** [umccr/elsa-data#272]
On an Elsa instance without AWS properly configured, if you navigate to the "AWS S3 VPC SHARE" tab in the "Access Data" pane, you'll see an alert pop up which keeps reappearing after being dismissed. The error appearing is expected; It's telling me about a legitimate problem with my configuration. The problem is specifically that the alert keeps reappearing after being dismissed, until you navigate to a different tab (e.g. "MANIFEST").

I suspect the main issue is that alerts are happening [here](https://github.com/umccr/elsa-data/blob/60b811d6896a5ca6a447f2cfbb5d84c1d13e668a/application/frontend/src/providers/trpc-provider.tsx#L28) when they should instead happen in a `useEffect` hook.

I think the alerts might also happen with less frequency if we tried harder to avoid unnecessary re-renders. ([Related thread](https://github.com/umccr/elsa-data/pull/254#discussion_r1142779932)). I've attached a video of the issue below. You can see that each time the component is re-rendered, it produces (an) alert(s) and makes (a) HTTP request(s). The alerts and network activity associated with that component continue until you navigate to a different tab.

https://user-images.githubusercontent.com/11529449/228955715-cbcb8aa1-5294-4b3f-b6e9-9d89a72147a3.mov

**Comment by DoxasticFox** [comment]
CC @andrewpatto @williamputraintan

**Comment by andrewpatto** [comment]
Yes @williamputraintan, thanks for the reports and suggestion @DoxasticFox  - I think it goes to my point that I think we need an "expired credential" mechanism that actually is doing something to do with the credential dates (for checking) - and not triggering off just HTTP codes (where there are other reasons why things can generate 401 or 403s).

Then following on from that - I'm not sure Alert() is ever needed for anything - have it set some cookie state or something - and have that rendered as a banner ("we noticed your credentials have expired")..

And then also - there is a broader issue to do with obviously the AWS Sharing boxes shouldn't be enabled  if you are running on a machine that has no AWS - but that's a thing I can deal with

**Comment by williamputraintan** [comment]
Yup, thanks for bringing this up! For now, I made [a change](https://github.com/umccr/elsa-data/pull/269/files#diff-17d29f12ec3767200cdbc355f3d8471a8c6246486db504c47474f105d8d0dfec)  (is now in dev branch) so that the alert is applicable to only 401 error only (I think the alert shouldn't show for the 500 network error call error now for this example). My thinking is user might confused if they got kicked out with no explanation. But yes, I do agree that should probably depend on the cookie who is responsible determining if user is logged in rather than an errorCode from the API.

I think for the double alert render,`React.StrictMode` should be responsible for this. It will simply render things twice to detect lifecycle problems. And after you close the first two alerts and pops another two, I think it should be `useQuery` which will retry the API when an error occurred (our setup currently will try 3 times before it stops), and so another alert will show ( and another one from `React.StrictMode`).

But yeah, I'm down for any optimisation to avoid unnecessary re-renders!
