### ISSUE TITLE
Long duration audit entries are visible even before completion

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#364]
Easy to have slipped through as we don't have many long operations - but when doing something like Copy Out that takes many minutes - the partially completed audit entry appears in the UI.

I presume we can just detect "partial" state in the service/query and remove - and we don't need to add an "inProgress" boolean to the db structure.

**Comment by mmalenic** [comment]
Ahh, I thought in-progress events should be shown in the UI, but thinking about it now, that doesn't really make sense.

**Comment by mmalenic** [comment]
I feel like the best solution for this would be to add an `inProgress` boolean to the audit events. Other solutions would be to identify partial audit events based on outcomes and descriptions, or by adding to the `details` property on the audit events. Although, I feel like this is more brittle because the format of the audit events could change. 

Another solution is to keep track of the in progress audit event ids inside `AuditEventService`, however I feel like this is more complicated because other services that call `AuditEventService` would need to make sure that the correct class instance is being used. This also has implications for multi-instance deployments, similar to the discussion in #352.

What do you think?

**Comment by andrewpatto** [comment]
Agree I'd be wary of any state information kept in the service itself (just say they restart the server during an hour long operation - we'd lose the ability to reconcile it).

Happy to add an `inProgress` boolean if there is no super obvious existing way of identifying partials..
