### ISSUE TITLE
User permissions shown in Edit perms dialog I think comes from UI permission knowledge - not backend

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#402]
Now that the backend database state is the sole arbiter of permissions - we probably need an API call where the UI asks for the backend permissions of users (or returns the permissions in the GetUsers call?) - rather than using anything known to the frontend. (note: I think it definitely already return the permissions of every user in the GetUsers call - so must be treating the "logged in user" differently)

Currently, I changed my own permissions in the UI - hit Save - then went back to the Edit dialog and the permissions had become unchecked.
(to be clear - the Change permissions had been correctly enacted - it just isn't reflected until I logout and login).

This is related to #401 - which previously immediately forced a login and so hid this.

**Comment by andrewpatto** [comment]
But you also finished this @williamputraintan ? Feel free to just close the issue - doesn't have to be tracked to the PR exactly

**Comment by williamputraintan** [comment]
Nope, the prev PR was only for the unify description. So this bug still presist.

**Comment by williamputraintan** [comment]
> I think it definitely already return the permissions of every user in the GetUsers call - so must be treating the "logged in user" differently)

Yes, information for its own permission is treated differently. 

So, if we decided to have an API to fetch the permissions of its user. Should we just abandon the use of `cookieForUI` and put all things at the user-context?

**Comment by andrewpatto** [comment]
I mean the GetUsers call does contain its own permissions yes?

The rationale for cookieForUI is that we can't continually hit the backend db asking what the permissions of the user is - so whether it be via cookies for UI or a single API call on login - something needs to bring this to the frontend and use it on every page for UI decisions (without refreshing that does anything with the backend).

I'm just saying - on the users page - where it literally *is* already making calls to the backend we should use that info.

**Comment by andrewpatto** [comment]
Yes sorry I wasn't clear in the ticket on re-read - I'm literally *just* talking here about when doing Edits on the user page. Not proposing changing the techniques elsewhere.

(and realising that means that the bits of the UI a user will see may differ from what they should see - i.e. the DAC menu -  if they change their own permissions - treating that as a separate problem).

The problem in the current situation is I can check the box giving me a permission - and then immediately go back into that same dialog box and the check box is unchecked. (all on the users page)

**Comment by williamputraintan** [comment]
> I mean the GetUsers call does contain its own permissions yes?

Yes, but the top permission box is sourced from the cookie not from the getUsers API. The top part and bottom currently on a seperate component (Only the bottom "other users" query the getUsers API).

I just had a thought that even if the top box (modifying own permission section) uses the same getUsers API, there will be a parsing/filter to pop out the current user permission box. I guess this is ok, but since we made the `other user` section paginate, I suppose this might complicate things like finding the current user or passing props here and there. Alternatively, the top part query just for its own user (probably with offset), and the bottom query its own for showing all users.

So what I had in mind is to have the cookie being replaced by a user-context similar on what we had on the ReleaseMasterData and use the `useOutletContext` and let every component used it. And am thinking this could replace the permission that we usually had for the `CookeForUI`.

**Comment by andrewpatto** [comment]
I mean there's already a hook that triggers on login - that goes to the backend and fetches things like "sharers" config etc..
it could totally fetch the permissions at the same time.
(I mean its kind of like the outlet context - same thing.. just a hook)

**Comment by andrewpatto** [comment]
sorry not a hook - a Provider. LoggedInUserConfigRelayProvider

**Comment by andrewpatto** [comment]
And yes - we could then drop the cookie for UI.

And further more - on the user editing their own permissions - all we'd need to do is invalidate the TRPC query for GetUserPermissions (assuming this is the new user call we introduce) - and I think the entire site would refresh with the new user permissions automatically
